name: Build Armbian Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "orangepizero2w"      # Custom target board
          armbian_release: "resolute"          # Custom OS target
          armbian_branch: "edge"               # Experimental rolling kernel
          armbian_target: "build"
          armbian_ui: "minimal"                # Enforces server/minimal CLI
          armbian_runner_clean: "yes"          # Purges workspace to save space
